# Notebook 2 – Data Inspection
# Objective

# The objective of this notebook is to inspect the Titanic dataset and understand its structure, dimensions, column names, data types, index, and basic statistics.

# Topics Covered

Number of rows and columns

Data types and column names

Index, shape, head(), tail(), and sample()

info() and describe()

dtypes and nunique()

value_counts()

Identification of numerical, categorical, date/time, identifier, and potential target columns

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
display(df.head())

Dataset loaded successfully!

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print("Dataset shape:", df.shape)

Number of rows: 891
Number of columns: 12
Dataset shape: (891, 12)

In [3]:
print("Column names:")
for column in df.columns:
    print(column)

Column names:
PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

In [4]:
print("Dataset index:")
print(df.index)

print("\nFirst 10 index values:")
print(df.index[:10])

Dataset index:
RangeIndex(start=0, stop=891, step=1)

First 10 index values:
RangeIndex(start=0, stop=10, step=1)

In [5]:
print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

print("5 random rows:")
display(df.sample(5, random_state=42))

First 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Last 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

5 random rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
709,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C
439,440,0,2,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,10.5000,NaN,S
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C

In [6]:
print("Dataset information:")
df.info()

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [7]:
print("Data type of each column:")
display(df.dtypes)

Data type of each column:

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [8]:
print("Numerical column statistics:")
display(df.describe())

print("Summary of all columns:")
display(df.describe(include="all"))

Numerical column statistics:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Summary of all columns:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [9]:
print("Unique values in each column:")
display(df.nunique())

Unique values in each column:

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [10]:
print("Passenger class counts:")
display(df["Pclass"].value_counts())

print("Survival counts:")
display(df["Survived"].value_counts())

print("Sex counts:")
display(df["Sex"].value_counts())

print("Embarkation port counts:")
display(df["Embarked"].value_counts(dropna=False))

Passenger class counts:

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

Survival counts:

Survived
0    549
1    342
Name: count, dtype: int64

Sex counts:

Sex
male      577
female    314
Name: count, dtype: int64

Embarkation port counts:

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [11]:
print("Jupyter is working")
print("DataFrame exists:", "df" in globals())

Jupyter is working
DataFrame exists: True

In [12]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (891, 12)

In [13]:
print("Step 1: Python is working")

try:
    import pandas as pd
    print("Step 2: Pandas is working")

    print("Step 3: Checking dataset")
    print("DataFrame exists:", "df" in globals())

    if "df" in globals():
        print("Dataset shape:", df.shape)
        print("Columns:", df.columns.tolist())

except Exception as e:
    print("ERROR TYPE:", type(e).__name__)
    print("ERROR MESSAGE:", e)

Step 1: Python is working
Step 2: Pandas is working
Step 3: Checking dataset
DataFrame exists: True
Dataset shape: (891, 12)
Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [14]:
print("Hello! Jupyter Notebook is working correctly.")

Hello! Jupyter Notebook is working correctly.

In [15]:
import pandas as pd

data = {
    "PassengerId": [1, 2, 3, 4, 5],
    "Age": [22, 38, 26, 35, 28],
    "Sex": ["male", "female", "female", "female", "male"],
    "Survived": [0, 1, 1, 1, 0]
}

df = pd.DataFrame(data)

print("Sample dataset created successfully!")
print("Dataset shape:", df.shape)

display(df)

Sample dataset created successfully!
Dataset shape: (5, 4)

   PassengerId  Age     Sex  Survived
0            1   22    male         0
1            2   38  female         1
2            3   26  female         1
3            4   35  female         1
4            5   28    male         0

In [16]:
print("Hello, Jupyter!")
print(2 + 3)

Hello, Jupyter!
5

In [17]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.3

In [18]:
print("Notebook 2: Data Inspection")
print("Step 1 completed")

Notebook 2: Data Inspection
Step 1 completed

In [19]:
import pandas as pd

df = pd.DataFrame({
    "PassengerId": [1, 2, 3, 4, 5],
    "Age": [22, 38, 26, 35, 28],
    "Sex": ["male", "female", "female", "female", "male"],
    "Survived": [0, 1, 1, 1, 0]
})

print("Rows and columns:", df.shape)
display(df)

Rows and columns: (5, 4)

   PassengerId  Age     Sex  Survived
0            1   22    male         0
1            2   38  female         1
2            3   26  female         1
3            4   35  female         1
4            5   28    male         0

In [20]:
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Column names:
['PassengerId', 'Age', 'Sex', 'Survived']

Data types:
PassengerId    int64
Age            int64
Sex              str
Survived       int64
dtype: object

In [21]:
print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

print("Dataset information:")
df.info()

print("Statistical summary:")
display(df.describe(include="all"))

First 5 rows:

   PassengerId  Age     Sex  Survived
0            1   22    male         0
1            2   38  female         1
2            3   26  female         1
3            4   35  female         1
4            5   28    male         0

Last 5 rows:

   PassengerId  Age     Sex  Survived
0            1   22    male         0
1            2   38  female         1
2            3   26  female         1
3            4   35  female         1
4            5   28    male         0

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  5 non-null      int64
 1   Age          5 non-null      int64
 2   Sex          5 non-null      str
 3   Survived     5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 318.0 bytes
Statistical summary:

        PassengerId        Age     Sex  Survived
count      5.000000   5.000000       5  5.000000
unique          NaN        NaN       2       NaN
top             NaN        NaN  female       NaN
freq            NaN        NaN       3       NaN
mean       3.000000  29.800000     NaN  0.600000
std        1.581139   6.572671     NaN  0.547723
min        1.000000  22.000000     NaN  0.000000
25%        2.000000  26.000000     NaN  0.000000
50%        3.000000  28.000000     NaN  1.000000
75%        4.000000  35.000000     NaN  1.000000
max        5.000000  38.000000     NaN  1.000000

In [22]:
print("Unique values in each column:")
display(df.nunique())

Unique values in each column:

PassengerId    5
Age            5
Sex            2
Survived       2
dtype: int64

In [23]:
print("Passenger ID counts:")
display(df["PassengerId"].value_counts())

print("\nSex counts:")
display(df["Sex"].value_counts())

print("\nSurvival counts:")
display(df["Survived"].value_counts())

Passenger ID counts:

PassengerId
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64

Sex counts:

Sex
female    3
male      2
Name: count, dtype: int64

Survival counts:

Survived
1    3
0    2
Name: count, dtype: int64

In [24]:
print("FINAL DATA INSPECTION SUMMARY")
print("-----------------------------")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData inspection completed successfully!")

FINAL DATA INSPECTION SUMMARY
-----------------------------
Number of rows: 5
Number of columns: 4

Column names:
['PassengerId', 'Age', 'Sex', 'Survived']

Missing values:
0

Duplicate rows:
0

Data inspection completed successfully!